package eu.janinko.andaria.staticcounter.staticcounter;

import eu.janinko.Andaria.ultimasdk.files.tiledata.ItemData;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author janinko
 */
public class StaticCounterUI extends javax.swing.JFrame {
	private StaticCounter sc = new StaticCounter();

	/**
	 * Creates new form StaticCounterUI
	 */
	public StaticCounterUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      uoPathField = new javax.swing.JTextField();
      x1Field = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      y1Field = new javax.swing.JTextField();
      jLabel3 = new javax.swing.JLabel();
      x2Field = new javax.swing.JTextField();
      y2Field = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      countButton = new javax.swing.JButton();
      jSplitPane1 = new javax.swing.JSplitPane();
      jScrollPane2 = new javax.swing.JScrollPane();
      table = new javax.swing.JTable();
      imageLabel = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Andaria Static Counter");

      jLabel1.setText("Cesta k ultimě:");

      uoPathField.setText("/home/janinko/Ultima/hra");
      uoPathField.setToolTipText("");
      uoPathField.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            uoPathFieldActionPerformed(evt);
         }
      });

      x1Field.setText("1000");

      jLabel2.setText("X1:");

      y1Field.setText("1000");

      jLabel3.setText("Y1:");

      x2Field.setText("1050");

      y2Field.setText("1050");

      jLabel4.setText("Y2:");

      jLabel5.setText("X2:");

      countButton.setText("Spočítat");
      countButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            countButtonActionPerformed(evt);
         }
      });

      table.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {

         },
         new String [] {
            "id", "Název", "Počet"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
         };
         boolean[] canEdit = new boolean [] {
            false, false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      table.getTableHeader().setReorderingAllowed(false);
      table.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tableMouseClicked(evt);
         }
      });
      jScrollPane2.setViewportView(table);

      jSplitPane1.setLeftComponent(jScrollPane2);
      jSplitPane1.setRightComponent(imageLabel);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel1)
                     .addComponent(jLabel2)
                     .addComponent(jLabel5))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(uoPathField, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(x1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                           .addComponent(x2Field))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jLabel3)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(y1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(y2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                  .addGap(18, 18, 18)
                  .addComponent(countButton)
                  .addGap(0, 0, Short.MAX_VALUE))
               .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(uoPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(x1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel2)
               .addComponent(y1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(x2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(y2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel4)
               .addComponent(jLabel5)
               .addComponent(countButton))
            .addGap(18, 18, 18)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void uoPathFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uoPathFieldActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_uoPathFieldActionPerformed

   private void countButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countButtonActionPerformed
		try{
			int x1 = Integer.parseInt(x1Field.getText());
			int y1 = Integer.parseInt(y1Field.getText());
			int x2 = Integer.parseInt(x2Field.getText());
			int y2 = Integer.parseInt(y2Field.getText());
			sc.setUOPath(uoPathField.getText());
			Map<ItemData, Integer> out = sc.getStatic(x1, y1, x2, y2);
			DefaultTableModel model = (DefaultTableModel) table.getModel();
			for(Map.Entry<ItemData, Integer> e : out.entrySet()){
				model.addRow(new Object[]{e.getKey().getId(), e.getKey().getName(), e.getValue()});
			}
		}catch(IOException ex){
			JOptionPane.showMessageDialog(this, "Špatná cesta!!" + System.getProperty("line.separator") + ex);
		}catch(NumberFormatException ex){
			JOptionPane.showMessageDialog(this, "Špatné číslo!!" + System.getProperty("line.separator") + ex);
		}
   }//GEN-LAST:event_countButtonActionPerformed

   private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
		try {
			int row = table.getSelectedRow();
			if(row == -1) return;
			Integer id = (Integer) table.getValueAt(row, 0);
			System.out.println("Selected id: " + id);
			BufferedImage myPicture = sc.getImage(id);
			if(myPicture == null){
				imageLabel.setIcon(null);
				return;
			}
			ImageIcon icon = new ImageIcon(myPicture);
			imageLabel.setIcon(icon);
		} catch (IOException ex) {
			Logger.getLogger(StaticCounterUI.class.getName()).log(Level.SEVERE, null, ex);
		}
   }//GEN-LAST:event_tableMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(StaticCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(StaticCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(StaticCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(StaticCounterUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new StaticCounterUI().setVisible(true);
			}
		});
	}
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton countButton;
   private javax.swing.JLabel imageLabel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JScrollPane jScrollPane2;
   private javax.swing.JSplitPane jSplitPane1;
   private javax.swing.JTable table;
   private javax.swing.JTextField uoPathField;
   private javax.swing.JTextField x1Field;
   private javax.swing.JTextField x2Field;
   private javax.swing.JTextField y1Field;
   private javax.swing.JTextField y2Field;
   // End of variables declaration//GEN-END:variables
}
